---
local_as: 65003
neighbors:
  - ip: "172.16.100.1"
    remote_as: 65001
  - ip: "172.16.100.9"
    remote_as: 65002
  - ip: "10.10.4.254"
    remote_as: 65004
advertised_networks:
  - ip: "10.10.4.0"
    mask: 24
